mkdir: missing operand
Try 'mkdir --help' for more information.
[E::hts_open_format] Failed to open file "/D3_metabat_output..fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output..fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
mkdir: missing operand
Try 'mkdir --help' for more information.
[E::hts_open_format] Failed to open file "/D3_metabat_output..fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output..fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
mkdir: missing operand
Try 'mkdir --help' for more information.
[E::hts_open_format] Failed to open file "/D3_metabat_output..fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output..fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
mkdir: missing operand
Try 'mkdir --help' for more information.
[E::hts_open_format] Failed to open file "/D3_metabat_output..fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output..fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
mkdir: missing operand
Try 'mkdir --help' for more information.
[E::hts_open_format] Failed to open file "/D3_metabat_output..fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output..fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
mkdir: missing operand
Try 'mkdir --help' for more information.
[E::hts_open_format] Failed to open file "/D3_metabat_output..fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output..fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
mkdir: missing operand
Try 'mkdir --help' for more information.
[E::hts_open_format] Failed to open file "/D3_metabat_output..fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output..fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
mkdir: missing operand
Try 'mkdir --help' for more information.
[E::hts_open_format] Failed to open file "/D3_metabat_output..fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output..fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
mkdir: missing operand
Try 'mkdir --help' for more information.
[E::hts_open_format] Failed to open file "/D3_metabat_output..fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output..fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
mkdir: missing operand
Try 'mkdir --help' for more information.
[E::hts_open_format] Failed to open file "/D3_metabat_output..fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output..fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
mkdir: missing operand
Try 'mkdir --help' for more information.
[E::hts_open_format] Failed to open file "/D3_metabat_output..fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output..fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
mkdir: missing operand
Try 'mkdir --help' for more information.
[E::hts_open_format] Failed to open file "/D3_metabat_output..fa_sort.bam" : No such file or directory
  [Errno 2] could not open alignment file `/D3_metabat_output..fa_sort.bam`: No such file or directory
  [Exception type: FileNotFoundError, raised in libcalignmentfile.pyx:941]
